# Generated by Django 4.0 on 2021-12-11 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dude_name',
            field=models.CharField(max_length=50, null=True, verbose_name='Dude naam'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(max_length=50, null=True, verbose_name='Voornaam'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(max_length=50, null=True, verbose_name='Achternaam'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='lichting',
            field=models.IntegerField(null=True, verbose_name='Lichting'),
        ),
    ]
