# Generated by Django 4.0 on 2021-12-19 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='user',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='user',
            name='dude_name',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Dude naam'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Voornaam'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Achternaam'),
        ),
        migrations.AlterField(
            model_name='user',
            name='lichting',
            field=models.IntegerField(blank=True, null=True, verbose_name='Lichting'),
        ),
    ]
