# Generated by Django 4.0 on 2021-12-11 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_dude_name_alter_profile_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dude_name',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Dude naam'),
        ),
    ]
