# Generated by Django 4.0 on 2021-12-19 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_remove_user_role_user_current_role_delete_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='lichting',
        ),
    ]
